version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: leetcode_user
      POSTGRES_PASSWORD: dev_password # Change in production
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leetcode_user -d leetcode"]
      interval: 10s
      timeout: 5s
      retries: 5 

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://leetcode_user:dev_password@db:5432/leetcode
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: your_jwt_secret_here
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest 