name: Process LeetCode Problems

on:
  workflow_run:
    workflows: ["Sync Leetcode"]
    types:
      - completed

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Create problems directory
        run: mkdir -p problems

      - name: Process problems
        run: go run scripts/process_problems.go

      - name: Rename problems in 0 directory
        run: |
          cd leetcode-db
          go run cmd/populate-db/main.go

      - name: Commit directory changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add problems/
          git add -u  # This will stage deletions of the old directories
          git commit -m "Move and rename problems" || echo "No changes to commit"
          git push 